### ISSUE TITLE
Features in nested folders created bad links

### ISSUE THREAD

**Issue by mikesalvia** [garethjevans/cucumber-slack-notifier-plugin#1]
There is no HTML file located at:
`http://jenkins/job/my_job/207/cucumber-html-reports/features/active/alpha/login.feature.html`

The correct link should look like this:
`http://jenkins/job/my_job/207/cucumber-html-reports/features-active-alpha-login-feature.html`

It appears `/` and `.` must be replaced with `-` at some point.

I will create a fork and try this out.

**Comment by carlosllanos12** [comment]
I'm having the same issue with the links, there is a way to solve that actually?

**Comment by mikesalvia** [comment]
I fixed this in a fork I can share modifications.

**Comment by mikesalvia** [comment]
@garethjevans Should I move this to the forked repo?

**Comment by carlosllanos12** [comment]
please can u share ur modifications?

**Comment by mikesalvia** [comment]
I no longer use this and have lost the changes.
